# Generated by Django 3.2 on 2024-11-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0003_auto_20241121_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='parts_category',
            field=models.CharField(choices=[('hair', '髪'), ('base', '素体'), ('eyes', '目'), ('clothes', '服'), ('accessory', 'アクセサリー'), ('background', '背景')], max_length=10),
        ),
    ]
