# Generated by Django 3.2 on 2024-11-26 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0004_alter_parts_parts_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='テキスト')),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_parts/', verbose_name='画像')),
                ('position', models.CharField(choices=[('top', '上部'), ('middle', '間'), ('bottom', '下部')], default='middle', max_length=10, verbose_name='画像の位置')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='順序')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='dress.question')),
            ],
            options={
                'verbose_name': '問題の一部',
                'verbose_name_plural': '問題の一部',
                'ordering': ['order'],
            },
        ),
    ]
