# Generated by Django 3.2 on 2024-11-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0005_questionpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='parts_gender',
            field=models.CharField(choices=[('male', '男性'), ('female', '女性')], max_length=10, null=True),
        ),
    ]
