# Generated by Django 3.2 on 2024-12-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_image',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/'),
        ),
    ]
