# Generated by Django 3.2 on 2024-12-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0009_alter_userprofile_avatar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='parts_category',
            field=models.CharField(choices=[('base', '素体'), ('hair', '髪'), ('eyes', '目'), ('clothes', '服'), ('accessory', 'アクセサリー'), ('background', '背景')], max_length=10),
        ),
    ]
