# Generated by Django 3.2 on 2024-12-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0010_alter_parts_parts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='parts_category',
            field=models.CharField(choices=[('base', '素体'), ('hair', '髪'), ('eyes', '目'), ('clothes', '服'), ('accessory', 'アクセサリー')], max_length=10),
        ),
    ]
