# Generated by Django 3.2 on 2025-01-14 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0011_alter_parts_parts_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dress.question')),
            ],
            options={
                'verbose_name': 'ランダムな問題',
                'verbose_name_plural': 'ランダムな問題',
            },
        ),
    ]
