# Generated by Django 3.2 on 2025-01-14 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dress', '0012_randomquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='randomquestion',
            options={},
        ),
        migrations.AddField(
            model_name='randomquestion',
            name='randomquest_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='randomquestion',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
            preserve_default=False,
        ),
    ]
