# Generated by Django 3.2 on 2025-01-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0013_auto_20250114_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomquestion',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='randomquestion',
            name='selected_choice',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
