# Generated by Django 3.2 on 2025-01-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0014_auto_20250117_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomquestion',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
