# Generated by Django 3.2 on 2025-01-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0016_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='random_question_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
