# Generated by Django 3.2 on 2025-01-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0017_review_random_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomquestion',
            name='id',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
