# Generated by Django 3.2 on 2025-01-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0018_alter_randomquestion_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='random_question_id',
        ),
        migrations.AlterField(
            model_name='randomquestion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
