# Generated by Django 3.2 on 2025-01-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0019_auto_20250121_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='randomquest_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
