# Generated by Django 3.2 on 2025-01-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0020_review_randomquest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_retry',
            field=models.BooleanField(default=False),
        ),
    ]
