# Generated by Django 3.2 on 2025-01-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0021_review_is_retry'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='unlock_rank',
            field=models.IntegerField(default=1, verbose_name='アンロックランク'),
        ),
    ]
