# Generated by Django 3.2 on 2025-01-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0022_parts_unlock_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='selected_parts',
            field=models.ManyToManyField(blank=True, to='dress.Parts'),
        ),
    ]
