# Generated by Django 3.2 on 2025-01-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='previous_rank',
            field=models.IntegerField(default=1),
        ),
    ]
